version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run start:dev

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
